CREATE SEQUENCE edt.seq_salle;
ALTER SEQUENCE edt.seq_salle OWNER TO "edtemps-ecn";
CREATE SEQUENCE edt.seq_materiel;
ALTER SEQUENCE edt.seq_materiel OWNER TO "edtemps-ecn";
CREATE SEQUENCE edt.seq_contientmateriel;
ALTER SEQUENCE edt.seq_contientmateriel OWNER TO "edtemps-ecn";
CREATE SEQUENCE edt.seq_typecalendrier;
ALTER SEQUENCE edt.seq_typecalendrier OWNER TO "edtemps-ecn";
CREATE SEQUENCE edt.seq_groupedeparticipant;
ALTER SEQUENCE edt.seq_groupedeparticipant OWNER TO "edtemps-ecn";
CREATE SEQUENCE edt.seq_evenement;
ALTER SEQUENCE edt.seq_evenement OWNER TO "edtemps-ecn";
CREATE SEQUENCE edt.seq_alieuensalle;
ALTER SEQUENCE edt.seq_alieuensalle OWNER TO "edtemps-ecn";
CREATE SEQUENCE edt.seq_necessitemateriel;
ALTER SEQUENCE edt.seq_necessitemateriel OWNER TO "edtemps-ecn";
CREATE SEQUENCE edt.seq_matiere;
ALTER SEQUENCE edt.seq_matiere OWNER TO "edtemps-ecn";
CREATE SEQUENCE edt.seq_calendrier;
ALTER SEQUENCE edt.seq_calendrier OWNER TO "edtemps-ecn";
CREATE SEQUENCE edt.seq_calendrierappartientgroupe;
ALTER SEQUENCE edt.seq_calendrierappartientgroupe OWNER TO "edtemps-ecn";
CREATE SEQUENCE edt.seq_evenementappartient;
ALTER SEQUENCE edt.seq_evenementappartient OWNER TO "edtemps-ecn";
CREATE SEQUENCE edt.seq_utilisateur;
ALTER SEQUENCE edt.seq_utilisateur OWNER TO "edtemps-ecn";
CREATE SEQUENCE edt.seq_proprietairegroupedeparticipant;
ALTER SEQUENCE edt.seq_proprietairegroupedeparticipant OWNER TO "edtemps-ecn";
CREATE SEQUENCE edt.seq_abonnegroupeparticipant;
ALTER SEQUENCE edt.seq_abonnegroupeparticipant OWNER TO "edtemps-ecn";
CREATE SEQUENCE edt.seq_responsableevenement;
ALTER SEQUENCE edt.seq_responsableevenement OWNER TO "edtemps-ecn";
CREATE SEQUENCE edt.seq_intervenantevenement;
ALTER SEQUENCE edt.seq_intervenantevenement OWNER TO "edtemps-ecn";
CREATE SEQUENCE edt.seq_proprietairecalendrier;
ALTER SEQUENCE edt.seq_proprietairecalendrier OWNER TO "edtemps-ecn";
CREATE SEQUENCE edt.seq_proprietairematiere;
ALTER SEQUENCE edt.seq_proprietairematiere OWNER TO "edtemps-ecn";
CREATE SEQUENCE edt.seq_typeutilisateur;
ALTER SEQUENCE edt.seq_typeutilisateur OWNER TO "edtemps-ecn";
CREATE SEQUENCE edt.seq_estdetype;
ALTER SEQUENCE edt.seq_estdetype OWNER TO "edtemps-ecn";
CREATE SEQUENCE edt.seq_droits;
ALTER SEQUENCE edt.seq_droits OWNER TO "edtemps-ecn";
CREATE SEQUENCE edt.seq_aledroitde;
ALTER SEQUENCE edt.seq_aledroitde OWNER TO "edtemps-ecn";
